// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_ITI_DB.Models;

public partial class ExamResult
{
    [Key]
    public int Id { get; set; }

    [StringLength(450)]
    public string UserId { get; set; }

    public int? ExamId { get; set; }

    public int? Score { get; set; }

    public int? TotalPoints { get; set; }

    /// <summary>
    /// Calculated as (Score/TotalPoints)*100
    /// </summary>
    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Percentage { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? DurationMinutes { get; set; }

    /// <summary>
    /// True when Percentage &gt;= PassThreshold
    /// </summary>
    public bool? IsPassed { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? PassThreshold { get; set; }

    public DateTime? CreatedDate { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("ExamResults")]
    public virtual Exam Exam { get; set; }

    [InverseProperty("ExamResult")]
    public virtual ICollection<StudentAnswer> StudentAnswers { get; set; } = new List<StudentAnswer>();

    [ForeignKey("UserId")]
    [InverseProperty("ExamResults")]
    public virtual ApplicationUser User { get; set; }
}