// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_ITI_DB.Models;

[Index("ExamId", "UserId", Name = "IX_ExamAssignments_ExamId_UserId", IsUnique = true)]
public partial class ExamAssignment
{
    [Key]
    public int Id { get; set; }

    public int? ExamId { get; set; }

    public string UserId { get; set; }

    public DateTime? AssignedDate { get; set; }

    public DateTime? DueDate { get; set; }

    public bool? IsCompleted { get; set; }

    public DateTime? CompletedDate { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("ExamAssignments")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ExamAssignments")]
    public virtual ApplicationUser User { get; set; }
}