// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_ITI_DB.Models;

public partial class Exam
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string Title { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Must be greater than 0
    /// </summary>
    public int? DurationMinutes { get; set; }

    public bool? IsActive { get; set; }

    public int? SubjectId { get; set; }

    public int? YearLevelId { get; set; }

    [StringLength(450)]
    public string CreatedById { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastUpdated { get; set; }

    [ForeignKey("CreatedById")]
    [InverseProperty("CreatedExams")]
    public virtual ApplicationUser CreatedBy { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<ExamAssignment> ExamAssignments { get; set; } = new List<ExamAssignment>();

    [InverseProperty("Exam")]
    public virtual ICollection<ExamResult> ExamResults { get; set; } = new List<ExamResult>();

    [InverseProperty("Exam")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [ForeignKey("SubjectId")]
    [InverseProperty("Exams")]
    public virtual Subject Subject { get; set; }

    [ForeignKey("YearLevelId")]
    [InverseProperty("Exams")]
    public virtual YearLevel YearLevel { get; set; }
}