// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_ITI_DB.Models;

public partial class Question
{
    [Key]
    public int Id { get; set; }

    public string Text { get; set; }

    public string Options { get; set; }

    [StringLength(255)]
    public string CorrectAnswer { get; set; }

    /// <summary>
    /// Must be greater than 0
    /// </summary>
    public int? Points { get; set; }

    public int? ExamId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastUpdated { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("Questions")]
    public virtual Exam Exam { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<StudentAnswer> StudentAnswers { get; set; } = new List<StudentAnswer>();
}