// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_ITI_DB.Models;

public partial class StudentAnswer
{
    [Key]
    public int Id { get; set; }

    [StringLength(450)]
    public string UserId { get; set; }

    public int? QuestionId { get; set; }

    public int? ExamResultId { get; set; }

    [StringLength(255)]
    public string Answer { get; set; }

    public bool? IsCorrect { get; set; }

    /// <summary>
    /// Cannot exceed Question.Points
    /// </summary>
    public int? PointsEarned { get; set; }

    public DateTime? CreatedDate { get; set; }

    [ForeignKey("ExamResultId")]
    [InverseProperty("StudentAnswers")]
    public virtual ExamResult ExamResult { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("StudentAnswers")]
    public virtual Question Question { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("StudentAnswers")]
    public virtual ApplicationUser User { get; set; }
}