// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_ITI_DB.Models;

[PrimaryKey("UserId", "SubjectId")]
public partial class UserSubject
{
    [Key]
    public string UserId { get; set; }

    [Key]
    public int SubjectId { get; set; }

    public DateTime? CreatedDate { get; set; }

    [ForeignKey("SubjectId")]
    [InverseProperty("UserSubjects")]
    public virtual Subject Subject { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserSubjects")]
    public virtual ApplicationUser User { get; set; }
}