// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_ITI_DB.Models;

public partial class YearLevel
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Code { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    public bool? IsActive { get; set; }

    [InverseProperty("YearLevel")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("YearLevel")]
    public virtual ICollection<ApplicationUser> Users { get; set; } = new List<ApplicationUser>();
}